# **Python Assignments: -**






# 1.Print all prime numbers between input range (Ex – input 20 50, prints all prime numbers between 20 and 50).

In [ ]:
m=int(input("Enter m value: "))
n=int(input("Enter n value: "))
for v in range(m,n+1):
  count=0
  for i in range(1,v+1):
    if(v%i==0):
      count+=1
  if(count==2):
    print(v,end=" ")


Enter m value: 20
Enter n value: 50
23 29 31 37 41 43 47 



#2. Factorial using recursion


In [ ]:
def fact(n):
  if n==0:
    return 1
  return n*fact(n-1)
n=int(input("Enter the value:"))
print(fact(n))

Enter the value:5
120


# 3.Square of numbers using lambda

In [ ]:
n=int(input("Enter the value"))
square=lambda x:x*x
print("Square value is:" ,square(n))

Enter the value7
Square value is: 49


# 4.Find the second largest element in a list

In [1]:
a=list(map(int,input("Enter the value:").split()))
largest=a[0]
second=a[0]
for x in a:
  if x>largest:
    second=largest
    largest=x
  elif x>second and x!=largest:
    second=x
print(second)

Enter the value:10 20 5 30 25
25


# 5.Count frequency of characters in a string

In [2]:
s = input()

for ch in s:
    count = 0

    for x in s:
        if ch == x:
            count += 1

    print(ch, count)

hello
h 1
e 1
l 2
l 2
o 1


# 6.Calculate area of a circle using math library.

In [4]:

import math

r = float(input("enter the value:"))

area = math.pi * r * r

print(area)

enter the value:25
1963.4954084936207


# 7.Reverse a string without using built‑in reverse

In [5]:
s = input("enter the value: ")

reverse = ""

for ch in s:
    reverse = ch + reverse

print(reverse)

enter the value: vaishu
uhsiav


# 8. Remove Duplicates From List

In [6]:
a = list(map(int, input("Enetr the value: ").split()))

b = []

for x in a:
    if x not in b:
        b.append(x)

print(b)

Enetr the value: 1 2 2 3 4 4 5
[1, 2, 3, 4, 5]


# 9. Merge Two Dictionaries

In [7]:
a = {"a": 1, "b": 2}
b = {"c": 3, "d": 4}

for key in b:
    a[key] = b[key]

print(a)

{'a': 1, 'b': 2, 'c': 3, 'd': 4}


# 10. Fibonacci Using Recursion

In [8]:
def fibonacci(n):
    if n <= 1:
        return n

    return fibonacci(n - 1) + fibonacci(n - 2)

n = int(input())

for i in range(n):
    print(fibonacci(i), end=" ")

14
0 1 1 2 3 5 8 13 21 34 55 89 144 233 

# **# Python Function Assignments:**

# 1.Write a function calculate(a, b, operation) that performs addition, subtraction, multiplication, or division based on the supplied operation.

In [10]:
def calculate(a, b, operation):
    if operation == "+":
        return a + b
    elif operation == "-":
        return a - b
    elif operation == "*":
        return a * b
    elif operation == "/":
        return a / b

a = int(input("Enter a: "))
b = int(input("Enter b: "))
operation = input("Enter operation: ")

print("values:",calculate(a, b, operation))

Enter a: 54
Enter b: 69
Enter operation: *
values: 3726


# 2.Write a function sum_numbers(*args) that accepts any number of arguments and returns their sum.

In [11]:
def sum_numbers(*args):
    total = 0

    for x in args:
        total = total + x

    return total

print(sum_numbers(10, 20, 30))

60



# 3.Write a function employee(**args) that accepts employee information such as name, ID, department and salary, then displays the information.

In [12]:
def employee(**args):
    for key, value in args.items():
        print(key, ":", value)

employee(name="Vaishu", ID=101, department="IT", salary=30000)

name : Vaishu
ID : 101
department : IT
salary : 30000


# 4.Write a function remove_duplicates(lst) that returns a list containing only unique elements while preserving their original order.

In [13]:
def remove_duplicates(lst):
    result = []

    for x in lst:
        if x not in result:
            result.append(x)

    return result

a = [1, 2, 2, 3, 1, 4]

print(remove_duplicates(a))

[1, 2, 3, 4]


# 5.Using a lambda function, sort a list of tuples based on the second element. Example: [(1,5), (2,3), (4,1)].

In [14]:
a = [(1, 5), (2, 3), (4, 1)]

a.sort(key=lambda x: x[1])

print(a)

[(4, 1), (2, 3), (1, 5)]


# **NUMPY ASSIGNMENT**

# Question 1 – Student Marks Array

In [15]:
import numpy as np

marks = np.array([78, 65, 89, 56, 92])

print("Array:", marks)
print("Shape:", marks.shape)
print("Size:", marks.size)
print("Data Type:", marks.dtype)
print("Dimensions:", marks.ndim)

Array: [78 65 89 56 92]
Shape: (5,)
Size: 5
Data Type: int64
Dimensions: 1


# 2. Student Marks Access

In [16]:
import numpy as np

marks = np.array([72, 85, 64, 90, 76])

print("First student:", marks[0])
print("Third student:", marks[2])

print("First three marks:", marks[0:3])
print("Last two marks:", marks[3:5])

First student: 72
Third student: 64
First three marks: [72 85 64]
Last two marks: [90 76]


# 3. Subject-wise Marks

In [17]:
import numpy as np

marks = np.array([78,85,90,65,72,80,88,91,84,56,62,70,95,89,92])

matrix = marks.reshape(5,3)

print(matrix)

[[78 85 90]
 [65 72 80]
 [88 91 84]
 [56 62 70]
 [95 89 92]]


# 4. Internal and External Marks

In [18]:
import numpy as np

internal = np.array([20, 18, 25, 22, 19])
external = np.array([60, 55, 65, 58, 62])

final = internal + external

print(final)

[80 73 90 80 81]


# 5. Pass Percentage Analysis

In [19]:
import numpy as np

marks = np.array([45, 78, 56, 32, 91])

pass_students = marks >= 50

print(pass_students)
print(marks[pass_students])

[False  True  True False  True]
[78 56 91]


# 6. Average Marks

In [20]:
import numpy as np

marks = np.array([
    [78,85,90],
    [65,72,80],
    [88,91,84],
    [56,62,70],
    [95,89,92]
])

avg = np.mean(marks, axis=1)

print(avg)

[84.33333333 72.33333333 87.66666667 62.66666667 92.        ]


# 7. Class Performance Statistics

In [21]:
import numpy as np

marks = np.array([67,82,91,74,58])

print("Total:", np.sum(marks))
print("Average:", np.mean(marks))
print("Highest:", np.max(marks))
print("Lowest:", np.min(marks))
print("Standard Deviation:", np.std(marks))

Total: 372
Average: 74.4
Highest: 91
Lowest: 58
Standard Deviation: 11.46472851837321


# 8. Subject-wise Performance

In [22]:
import numpy as np

marks = np.array([
    [78,85,90],
    [65,72,80],
    [88,91,84],
    [56,62,70],
    [95,89,92]
])

subject_total = np.sum(marks, axis=0)

print(subject_total)

[382 399 416]


# 9. Student-wise Performance

In [23]:
import numpy as np

marks = np.array([
    [78,85,90],
    [65,72,80],
    [88,91,84],
    [56,62,70],
    [95,89,92]
])

student_total = np.sum(marks, axis=1)

print(student_total)

[253 217 263 188 276]


# 10. Student Ranking

In [24]:
import numpy as np

marks = np.array([245,278,219,290,256])

sorted_marks = np.sort(marks)

print("Sorted:", sorted_marks)

rank = np.argsort(marks)

print("Rank Index:", rank)

Sorted: [219 245 256 278 290]
Rank Index: [2 0 4 1 3]


# 11. Duplicate Marks Analysis

In [25]:
import numpy as np

marks = np.array([85,92,85,76,92])

unique_marks = np.unique(marks)

print(unique_marks)

[76 85 92]


# 12. Missing Marks

In [26]:
import numpy as np

marks = np.array([78,85,np.nan,92,67])

avg = np.nanmean(marks)

print(avg)

80.5


# 13 – Grade Classification

In [27]:
import numpy as np

marks = np.array([95,82,74,61,45])

for m in marks:
    if m >= 90:
        print(m, "A")
    elif m >= 75:
        print(m, "B")
    elif m >= 60:
        print(m, "C")
    else:
        print(m, "D")

95 A
82 B
74 C
61 C
45 D


# 14. Random Marks Generation

In [28]:
import numpy as np

marks = np.random.randint(40,100,5)

print("Marks:", marks)

print("Average:", np.mean(marks))
print("Highest:", np.max(marks))
print("Lowest:", np.min(marks))

Marks: [95 92 82 46 80]
Average: 79.0
Highest: 95
Lowest: 46


# 15 – Complete Student Analysis

In [29]:
import numpy as np

marks = np.array([
    [78,85,90],
    [65,72,80],
    [88,91,84],
    [56,62,70],
    [95,89,92]
])

total = np.sum(marks, axis=1)

average = np.mean(marks, axis=1)

highest = np.max(marks, axis=1)

lowest = np.min(marks, axis=1)

class_avg = np.mean(total)

print("Total:", total)
print("Average:", average)
print("Highest:", highest)
print("Lowest:", lowest)

print("Class Average:", class_avg)

print("Above Class Average:")

for i in range(len(total)):
    if total[i] > class_avg:
        print("Student", i+1)

Total: [253 217 263 188 276]
Average: [84.33333333 72.33333333 87.66666667 62.66666667 92.        ]
Highest: [90 80 91 70 95]
Lowest: [78 65 84 56 89]
Class Average: 239.4
Above Class Average:
Student 1
Student 3
Student 5
